### ISSUE TITLE
Can't build on debian 6.0.6

### ISSUE THREAD

**Issue by oleksandr-l5** [OpenRTMFP/Cumulus#88]
creating CumulusServer executable CumulusServer
LUAGroups.o: In function `LUAGroups::Join(lua_State*)':
LUAGroups.cpp:(.text+0x2ba6): undefined reference to`Cumulus::Peer::joinGroup(unsigned char const_, Cumulus::FlowWriter_)'
Server.o:(.rodata._ZTV6Server[vtable for Server]+0x14): undefined reference to `Cumulus::RTMFPServer::createSession(Cumulus::Peer const&, Cumulus::Cookie&)'
Server.o:(.rodata._ZTV6Server[vtable for Server]+0x110): undefined reference to`non-virtual thunk to Cumulus::RTMFPServer::run()'
Server.o:(.rodata._ZTV6Server[vtable for Server]+0x120): undefined reference to `non-virtual thunk to Cumulus::RTMFPServer::onReadable(Poco::Net::Socket&)'
Server.o:(.rodata._ZTV6Server[vtable for Server]+0x124): undefined reference to`non-virtual thunk to Cumulus::RTMFPServer::onError(Poco::Net::Socket const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ServerConnection.o: In function `ServerConnection::send(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ServerMessage&)':
ServerConnection.cpp:(.text+0x1204): undefined reference to`Cumulus::BinaryStream::resetWriting(unsigned int)'
ServerConnection.cpp:(.text+0x1280): undefined reference to `Cumulus::BinaryStream::resetWriting(unsigned int)'
ServerConnection.cpp:(.text+0x1338): undefined reference to`Cumulus::Logs::Dump(unsigned char const_, unsigned int, char const_)'
ServerConnection.o: In function `Cumulus::Logs::Dump(Cumulus::PacketReader&, char const*)':
ServerConnection.cpp:(.text._ZN7Cumulus4Logs4DumpERNS_12PacketReaderEPKc[Cumulus::Logs::Dump(Cumulus::PacketReader&, char const*)]+0x2e): undefined reference to`Cumulus::Logs::Dump(unsigned char const_, unsigned int, char const_)'
collect2: ld returned 1 exit status
make: **\* [main] Error 1

gcc -v
Using built-in specs.
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.4.5-8' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.4 --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.4.5 (Debian 4.4.5-8)
